### ISSUE TITLE
PingPong перед ping по вебсокетам

### ISSUE THREAD

**Issue by asn007** [Yashko/node-csgotm#1]
В [документации](http://csgo.tm/docs) указано, что перед тем, как отправить ping, нужно выполнить запрос PingPong к API. 

Цитирую:

"ВНИМАНИЕ! Для нахождения в онлайне и продажи вещей необходимо отправлять команду ping раз минуту предварительно единожды отправив запрос к API методом PingPong"

Возможно я ошибаюсь, но этого функционала в библиотеке нет. Создать pull request?

**Comment by Yashko** [comment]
Добавил этот функционал в a2290d1c41f0aaa5cab92a091a1cad7a27502cb4
